first commit
GO-SOPT-ANDROID/nayeong-lee pull request #1
Opened 2023-04-05 06:22 UTC by Bewheneverwhatiwant

이렇게하면 끝난건가...???

2023-04-05 06:32 UTC, Bewheneverwhatiwant commented
이건 뭐지???

2023-04-07 14:40 UTC, SeonHwan-Kim commented
파일 이름 hi 말고 무슨 뷰인지 알 수 있게 바꾸면 좋을 것 같아요

2023-04-07 14:44 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/MainActivity.kt
> +        val tv_6 = findViewById<Button>(R.id.tv_6)
이런 것들도 tv_6라고 하면 나중에 이게 뭔지 알기 어려우니 조금 더 자세하게 써주세요!

2023-04-07 14:44 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/MainActivity.kt
> +            if((id.length >= 6) && (id.length<=10)) {
&&로 묶는 대신 in 6..10 이런 것도 있으니 확인해보세용

2023-04-08 07:53 UTC, SeonHwan-Kim commented on app/src/main/java/org/android/go/sopt/MainActivity.kt
> +        val tv_3 = findViewById<EditText>(R.id.tv_3)
findViewById 대신 binding 사용하기

2023-04-08 08:55 UTC, daehwan2da requested changes

2023-04-08 08:55 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/MainActivity.kt
> +        val tv_6 = findViewById<Button>(R.id.tv_6)
viewBinding 을 쓰면 findBiewById() 가 필요없을 것 같네요..

2023-04-08 08:55 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/MainActivity.kt
> +    private var mBinding:ActivityMainBinding? = null
1주차 세미나인데 null binding 을 쓰셨는데, 혹시 알고 쓴건지? 아니면 따라친건지..

2023-04-08 08:55 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/hi2.kt
> +            startActivity(intent)
Hi2 에서 MainActivity 로 이동하게 되면 Hi2 Activity 는 어떻게 처리하면 좋을까요?

2023-04-08 08:55 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/hi3.kt
> +        a_2.text = id
음 text 에 값을 바로 넣는것을 좋지 않을것같은데.. 이유는 무엇일까요?

- a_2.text 는 어떤 클래스이고, intent 에서 getStringExtra 로 뽑아왔을때는 어떤 클래스인지 알면 좋을것같아요
- TextView 에 어떤 method 들이 있는지 찾아보면 좋을것같아요

2023-04-29 12:50 UTC, closed without merging